In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

# A Python library is a collection of pre-written code that provides functionalities to perform specific tasks. We use Python libraries to save time and effort by leveraging existing code 
# for tasks like numerical computation, data analysis, web development, and more. Libraries extend Python's capabilities beyond its built-in functions, 
# allowing developers to work more efficiently and effectively 

In [ ]:
# # 2. What is the difference between Numpy array and List?

# Lists are native Python data structures, whereas NumPy arrays are objects provided by the NumPy library .
# NumPy arrays are homogeneous, meaning they can only contain elements of the same data type, whereas lists can hold elements of different data types.
# NumPy arrays offer better performance for numerical computations and operations compared to lists, especially when dealing with large datasets 

In [1]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12] ])

In [4]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr1.shape

(3, 4)

In [6]:
arr1.size

12

In [7]:
arr1.ndim

2

In [8]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
first_row = arr2[0]

In [13]:
first_row

array([1, 2, 3, 4])

In [26]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

In [27]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr3[2,3]

12

In [32]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [33]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
odd_elements = arr4[1::2]

In [37]:
odd_elements

array([[5, 6, 7, 8]])

In [42]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
import random


In [52]:
ar = np.random.randint(0,1,(3,3))

In [53]:
ar

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?
np.random.rand: This function generates random numbers from a uniform distribution over the interval [0, 1). It takes dimensions as arguments and returns an array of the specified shape
filled with random numbers. Each element in the output array is sampled independently and uniformly from the interval [0, 1)
                                                                                                                       
np.random.randn: In contrast, this function generates random numbers from a standard normal distribution (mean=0, variance=1), also known as the standard Gaussian distribution. 
Like np.random.rand, it also takes dimensions as arguments and returns an array of the specified shape filled with random numbers. However, the numbers generated by np.random.randn 
follow a bell-shaped curve around 0, with most values clustering near the mean (0) and tapering off towards positive and negative infinity                                                                                                                       

In [58]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr5 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [59]:
a = np.expand_dims(arr5, axis = 1)

In [60]:
a

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [61]:
a = np.expand_dims(arr5, axis = 0)

In [62]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [63]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [64]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr6.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [88]:
# 11. Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1index wiLe multiplication
# 2 Matix multiplication
# 3 Add both the maticK
# 4 Subtact matix B om 
# 5 Divide Matix B by A

a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [89]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
# 1 index wiLe multiplication
a1*a2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [104]:
b1 = np.array([[[1,2],[3,4]]])
b2 = np.array([[1,2],[3,4]])

In [105]:
# 2 Matix multiplication
b1 @ b2

#I am very confused here, when I am doing matrix multilication here it is running smothly while

array([[[ 7, 10],
        [15, 22]]])

In [98]:
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [99]:
a1 @ a2
#when i am running it here it is giving error, why is it happenning martix multiplcation dosen't care about the dimension until it is 2d or greater than 2d,
# number of elements are also same in a1 and a2 even the dimensions are same then why is it not working? why is it trhowing this error (size 3 is different from 4)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [79]:
# 3 Add both the maticK
a1 +a2

array([[ 2,  8,  6,  8],
       [ 7, 12, 14, 16],
       [10, 25, 22, 24]])

In [80]:
# 4 Subtact matix B om 
a1 - a2

array([[ 0, -4,  0,  0],
       [ 3,  0,  0,  0],
       [ 8, -5,  0,  0]])

In [102]:
# 5 Divide Matix B by A
a1/a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
12. Which function in Numpy can be use^ to swap the byte order of an array?
:- The function in NumPy used to swap the byte order of an array is numpy.ndarray.byteswap() 



13. What is the significance of the np.linalg.inv function?
The np.linalg.inv function in NumPy is significant as it calculates the inverse of a square matrix. This is useful in various mathematical computations, 
such as solving systems of linear equations, calculating eigenvalues, and more



14. What does the np.reshape function ^o, an^ how is it use^?
The np.reshape function in NumPy is used to change the shape of an array without changing its data. It takes the array to be reshaped and the new shape as arguments. 
This function is useful for tasks like converting a 1D array into a 2D array or vice versa, or resizing an array to fit the desired dimensions for computation 



15. What is broadcasting in Numpy?
Broadcasting in NumPy refers to the ability to perform arithmetic operations between arrays of different shapes. NumPy automatically broadcasts arrays to perform element-wise operations, 
making it possible to operate on arrays with different dimensions and shapes without explicitly creating multiple copies of the data. Broadcasting simplifies code and improves 
performance in array operations